language: ruby
sudo: false
rvm: 2.4.0
env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake db:schema:load --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - bundle exec rake db:migrate
  - bundle exec rails assets:precompile
install: 
  - bundle install --jobs=3 --retry=3
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn
