source 'https://rubygems.org'

# ruby '2.1.4'
#ruby '2.2.5'
ruby '2.4.0'
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
#gem 'rails', '4.2.1'
gem 'rails', '~> 5.0.0', '>= 5.0.0.1'
gem 'rails-i18n'
# Use postgresql as the database for Active Record
gem 'pg'
gem 'activeadmin', '~> 1.0.0.pre5'
gem 'inherited_resources', '~> 1.7'
gem 'webpacker'
gem 'foreman'
# Use Puma as the app server
gem 'puma', '~> 3.0'
gem 'sass-rails'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'vuejs-rails'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'rake'
gem 'simple_form'
gem 'nokogiri'
gem 'interactor'
gem 'seedbank'
gem 'devise'
gem 'bcrypt'
gem 'rolify'
gem 'pundit'
gem 'flickraw'
gem 'faraday'
gem 'figaro'
gem 'carrierwave'
gem 'rmagick'
#gem 'mini_magick'
gem 'fog-aws'
gem 'rails_12factor', group: :production
gem 'levenshtein'
gem 'whenever', require: false
gem 'http_accept_language'
gem 'routing-filter'
gem 'rollbar'
gem 'newrelic_rpm'
gem 'responders'

group :development, :test do
  gem 'rspec-rails'
  gem 'capybara'
  gem 'factory_girl_rails'
end
